### ISSUE TITLE
Logs in but crashes

### ISSUE THREAD

**Issue by InternetMedicineMan** [ghidorsi/install-party-parrots-slack#4]
Everything is installed and I get it loaded and logged into Slack but then it says the following:

`Login has been successfully made, are you feeling the parrots already??

/usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': no such element: Unable to locate element: {"method":"class name","selector":"c-dialog__go"} (Selenium::WebDriver::Error::NoSuchElementError)
  (Session info: chrome=84.0.4147.105)
  (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Mac OS X 10.13.6 x86_64)
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/oss/bridge.rb:547:in `find_element_by'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/search_context.rb:60:in `find_element'
	from base.rb:85:in `block in <main>'
	from base.rb:64:in `each'
	from base.rb:64:in `<main>'`

Any idea what is missing here?

**Comment by ghidorsi** [comment]
Yep, seems like they have removed the class which we used to find the submit button when adding the emoji. I'll fix that!

**Comment by ghidorsi** [comment]
@InternetMedicineMan this was fixed on 9d0df92d89e6d948d7ba9ee7410c89ea81116356.

Thanks for reporting the issue!
