### ISSUE TITLE
Selenium error

### ISSUE THREAD

**Issue by geoglrb** [ghidorsi/install-party-parrots-slack#5]
Hi,

So glad to see this repo! My apologies if this is some basic config error on my part, but I get the following error:

`Now that we have it all, lets do this! :fast_parrot:

Login has been successfully made, are you feeling the parrots already??

Traceback (most recent call last):                                                                                                                            |
	12: from base.rb:67:in `<main>'
	11: from base.rb:67:in `each'
	10: from base.rb:90:in `block in <main>'
	 9: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/element.rb:74:in `click'
	 8: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/oss/bridge.rb:328:in `click_element'
	 7: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/oss/bridge.rb:587:in `execute'
	 6: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	 5: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	 4: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
	 3: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
	 2: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
	 1: from /Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/Users/luke/.rvm/gems/ruby-2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok': unknown error: Element <button class="c-button c-button--primary c-button--medium c-button--disabled null--primary null--medium null--disabled" type="button" data-qa="customize_emoji_add_dialog_go" disabled="">...</button> is not clickable at point (584, 530). Other element would receive the click: <div class="c-sk-modal_footer_actions">...</div> (Selenium::WebDriver::Error::UnknownError)
  (Session info: headless chrome=84.0.4147.105)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.15.6 x86_64)`

**Comment by geoglrb** [comment]
Note that I believe this is happening when there is already an emoji with that name--I was uploading the parrots to a slack with a legacy set of parrots. Anyway, I was able to modify the script to get it to do what I needed, but I don't know if you want my code, as I have never used Ruby or Selenium before and I very well did things in a way that you wouldn't prefer.

**Comment by ghidorsi** [comment]
Hey @geoglrb, glad that you were able to find out what the issue was. Can you open a pull request with your changes? Or maybe describe here what you changed so I can adapt the code?

Regards.

**Comment by ghidorsi** [comment]
The issue was fixed

c868aacbc256af6cddbe411e6af297e85da3faf7

**Comment by geoglrb** [comment]
Thanks and apologies! I totally missed this.
