### ISSUE TITLE
Selenium error - unable to locate element

### ISSUE THREAD

**Issue by chazzmoney** [ghidorsi/install-party-parrots-slack#6]
Now that we have it all, lets do this! :fast_parrot:

Login has been successfully made, are you feeling the parrots already??

Parroting your slack!: |==================================================================================================================================================================|
Traceback (most recent call last):
	2: from base.rb:65:in `<main>'
	1: from base.rb:59:in `block in <main>'
/Library/Ruby/Gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/wait.rb:73:in `until': timed out after 45 seconds (no such element: Unable to locate element: {"method":"xpath","selector":"//button[@data-qa='customize_emoji_add_button']"} (Selenium::WebDriver::Error::TimeoutError)
  (Session info: headless chrome=85.0.4183.102))

**Comment by ghidorsi** [comment]
@chazzmoney Can you try again? I think that it was caused by the newest parrot URL and chrome headless.

If it doesn't work, can you provide which chromedriver version are you running?
